---
- name: Update netbox directories
  ansible.builtin.file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - env

- name: Update environment files
  ansible.builtin.template:
    src: "env/{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/env/{{ item }}"
    mode: "0644"
  loop:
    - netbox.env
    - postgres.env
    - redis-cache.env
    - redis.env

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
    - extra.py

- name: Remove outdated files
  ansible.builtin.file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: absent
  loop:
    - netbox.env
    - configuration/configuration.py
    - configuration/gunicorn_config.py

- name: Check if Netbox is running
  community.docker.docker_container_info:
    name: "{{ netbox_container_name }}"
  register: netbox_container_status

- name: Conditionally notify the Restart Netbox handler
  ansible.builtin.command: echo "Restarting Netbox"
  notify: Restart Netbox
  when: not netbox_container_status.exists or netbox_container_status.docker_container.State.Running == false
